learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all topics
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing the entry.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views
app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    public = models.BooleanField()


    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        """Return a string representation of the model."""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    public = forms.BooleanField(required=False)
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
        

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}
        

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from . models import Topic, Entry
from . forms import TopicForm, EntryForm
from django.db.models import Q

def index(request):
    """The home page for Learning Log."""
    print(request.user)
    if request.user.is_authenticated == True:
        last_topic = Topic.objects.filter(Q(owner=request.user) | Q(public=True)).last()
        context = {'last_topic': last_topic}
        return render(request, 'learning_logs/index.html', context)
    else:
        public_topics = Topic.objects.filter(public=True).order_by('-id')[:3]
        context = {'public_topics': public_topics}
        return render(request, 'learning_logs/index.html', context)

@login_required
def topics(request):
    """Show user's and public topics"""
    topics = Topic.objects.filter(Q(owner=request.user) | Q(public=True)).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = get_object_or_404(Topic, id=topic_id)

    check_topic_visibility(request, topic)

    entries = topic.entry_set.order_by('date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new toppic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; create a blank form.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.public = form.cleaned_data['public']
            print(new_topic.public)
            check_topic_owner(request, new_topic)
            new_topic.save()
            return redirect('learning_logs:topics')
    
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = get_object_or_404(Topic, id=topic_id)
    check_topic_visibility(request, topic)
    if request.method != 'POST':
        #No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.owner = request.user
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    # Display a blank or invalid form
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)
    
@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry"""
    entry = get_object_or_404(Entry, id=entry_id)
    topic = entry.topic
    
    check_entry_owner(request, entry)
    
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

def check_topic_owner(request, topic):
    """ Check if the topic belongs to the current user."""
    if topic.owner != request.user:
        raise Http404

def check_topic_visibility(request, topic):
    """ Check if the topic is not public"""
    if topic.public != True:
        # Make sure the topic belongs to the current user
        check_topic_owner(request, topic)

def check_entry_owner(request, entry):
    """ Check if the entry belongs to the current user."""
    if entry.owner != request.user:
        raise Http404

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('learning_logs:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-witdth, initial-scale=1,
    shrink-to-fit=no">
  <title>Learning Log</title>
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
</head>

<body>
  <div class="container">
  <nav class="navbar navbar-expand-lg mb-4 border navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'learning_logs:index'%}">
      Learning Log </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"> <style></style></span>
      </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'learning_logs:topics'%}">
            Topics </a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="navbar-text">Hello, {{ user.username }}.</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register'%}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login'%}">Log in</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</div>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {%block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h2>Edit entry:</h2>
{% endblock page_header %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<form method="post" action="{% url 'learning_logs:edit_entry' entry.id %}" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button name="submit" class="btn btn-primary">Save changes</button>
  {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<div class="jumbotron">
    <h1 class="display-3">Track your learning</h1>

    <p class="lead">Make your own Learning Log, and keep a list of the
        topics you're learning about. Whenever you learn something new
        about a topic, make an entry summarizing what you've learned.</p>
        <hr class="my-4">
        <p>It is free and it always will be for free.</p>
    {% if user.is_authenticated %}
    <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics'%}" role="button">Start Learning &raquo;</a>
    {% else %}
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
    {% endif %}
</div>

<div class="card">
    <div class="card-header">
      Quote of the day.
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p> ‘Never let formal education get in the way of your learning.’</p>
        <footer class="blockquote-footer"><cite title="Source Title">Mark Twain</cite></footer>
      </blockquote>
    </div>
  </div>

    {% if user.is_authenticated %}
  
    <div class="row mt-5">

        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Got interested in new subject?</h5>
              <p class="card-text">Add new topic to save the information.</p>
              <a href="{% url 'learning_logs:new_topic' %}" class="btn btn-primary">Add new topic</a>
            </div>
          </div>
        </div>

        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ last_topic }}</h5>
              <p class="card-text">The last subject was added by {{ last_topic.owner }}</p>
              <a href="{% url 'learning_logs:topic' last_topic.id %}" class="btn btn-primary">Check it out!</a>
            </div>
          </div>
        </div>
      </div>

  </div>
  {% else %}

  <div class="card mt-5 mx-auto">
    <div class="card-header">
      If you're registered you can contribute to public subjects such us:
    </div>
    {% for public_topic in public_topics %}
    <ul class="list-group list-group-flush">
      <li class="list-group-item">{{ public_topic }}</li>
      {% empty %}
      <li class="list-group-item">No topics yet.</li>
    </ul>
    {% endfor %}
  </div>

  {% endif %}
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>Add a new entry:</h2>
{% endblock page_header %}

{% block content %}
  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <form method="post" action="{% url 'learning_logs:new_entry' topic.id %}" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Add entry</button>
    {% endbuttons %}
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>Add a new topic:</h2>
{% endblock page_header %}

{% block content %}
 <form method="post" action="{% url 'learning_logs:new_topic' %}" class="form" >
     {% csrf_token %}
     {% bootstrap_form form %}
     {% buttons %}
      <button name="submit" class="btn btn-primary">Add topic</button>
    {% endbuttons %}
 </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
   <h3>{{ topic }}</h3>
   <h5>This topic belongs to user: {{ topic.owner }} </h5>
{% endblock page_header %}

{% block content %}
<p>
   <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry </a>
</p>

{% for entry in entries %}
<div class="card mb-3">
   <h4 class="card-header">
      {{ entry.date_added|date:'M d, Y H:i' }} - {{entry.owner}}
      {% if entry.owner == request.user %}
      <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
         Edit entry </a></small>
      {% endif %}
   </h4>
   <div class="card-body">
      {{ entry.text|linebreaks }}
   </div>
   
</div>
{% empty %}
<p>There are no entries for this topic yet</p>
{% endfor %}


{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<div style="overflow: hidden;">
   <h1 style="float: left;"> Topics</h1>
   <h2 style="float: right;"><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h2>
</div>

{% endblock page_header %}

{% block content %}


{% for topic in topics %}
<div class="card mt-5">
   {% if topic.public == True %}
   <h5 class="card-header">This topic is public.</h5>
   {% else %}
   <h5 class="card-header">This topic is private. Only you can see it and contribute to it.</h5>
   {% endif %}
   <div class="card-body">
      <h5 class="card-title"><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h5>
      <p class="card-text">This topic belongs to {{ topic.owner }}.</p>
      <a href="{% url 'learning_logs:topic' topic.id %}" class="btn btn-primary">learn now</a>
   </div>
</div>
{% empty %}
<div class="card-body">
   <h5 class="card-title">>No topics have been added yet.</h5>
</div>
{% endfor %}

{% endblock content %}